// ═══════════════════════════════════════════════════════════════
// LAST LIGHT — Configuration
// ═══════════════════════════════════════════════════════════════

export const CFG = {
    beam: {
        maxAngularVel: 2.2,
        angularAccel: 8.0,
        angularDamping: 0.88,
        coneAngle: 0.38,
        coneLength: 0.82,
        fuelMax: 100,
        fuelDrain: 4,
        fuelRegen: 6,
        overdriveDrain: 30,
        overdriveMultiplier: 0.15,
    },
    ships: {
        skiffSpeed: 45,
        merchantSpeed: 22,
        passengerSpeed: 20,
        ghostShipSpeed: 12,
        skiffFlashNeed: 0.6,
        skiffDriftTime: 5.0,
        merchantGuideRate: 0.015,
        merchantDriftRate: -0.003,
        ghostShipRevealDist: 0.3,
        ghostShipLureRadius: 200,
    },
    creatures: {
        lurkerSpeed: 30,
        lurkerFleeSpeed: 80,
        lurkerFleeDuration: 2.0,
        flinchSpeed: 70,
        flinchFreezeTime: 0.8,
        flinchBoltSpeed: 120,
        flinchBoltDuration: 0.6,
        mimicSpeed: 40,
        mimicRevealDist: 0.3,
        abyssalSpeed: 15,
        abyssalSize: 40,
        abyssalPushback: 150,
        shadeSpeed: 25,
        shadeDamageTime: 8.0,
    },
    night: {
        duration: 120,
        dawnTransition: 3.0,
    },
    colors: {
        darkWater: '#0a1628',
        deepSky: '#060d1a',
        stone: '#3a3530',
        stoneLight: '#5a5548',
        beam: '#ffcc44',
        beamPale: '#fff8e0',
        beamDim: '#aa8822',
        harbor: '#ffcc44',
        lantern: '#ffaa33',
        danger: '#ff4444',
        creature: '#12081a',
        creatureEye: '#8844aa',
        wreckage: '#4a3828',
        horizon: '#0d1e38',
        horizonGlow: 'rgba(20,35,60,0.6)',
    },
    // Night configs
    nights: [
        { // Night 1: Skiffs + 1 lurker to teach threat early
            skiffs: 4, merchants: 0, passengers: 0, ghostShips: 0,
            lurkers: 1, flinches: 0, mimics: 0, abyssals: 0, shades: 0,
            spawnInterval: [5, 9], duration: 50,
            desc: "The sea is calm. Guide the skiffs to harbor.",
        },
        { // Night 2: Skiffs + Merchant + lurkers
            skiffs: 4, merchants: 1, passengers: 0, ghostShips: 0,
            lurkers: 2, flinches: 0, mimics: 0, abyssals: 0, shades: 0,
            spawnInterval: [5, 10], duration: 75,
            desc: "A merchant vessel approaches. Hold the beam steady.",
        },
        { // Night 3: Lurkers ramp up
            skiffs: 5, merchants: 1, passengers: 0, ghostShips: 0,
            lurkers: 4, flinches: 0, mimics: 0, abyssals: 0, shades: 0,
            spawnInterval: [5, 9], duration: 90,
            desc: "Something moves beneath the surface.",
        },
        { // Night 4: Growing threat
            skiffs: 6, merchants: 2, passengers: 0, ghostShips: 0,
            lurkers: 6, flinches: 0, mimics: 0, abyssals: 0, shades: 0,
            spawnInterval: [5, 9], duration: 90,
            desc: "The dark is restless tonight.",
        },
        { // Night 5: Flinches + passengers
            skiffs: 5, merchants: 2, passengers: 1, ghostShips: 0,
            lurkers: 5, flinches: 3, mimics: 0, abyssals: 0, shades: 0,
            spawnInterval: [5, 8], duration: 90,
            desc: "Quick shapes dart at the edges. A passenger vessel among them.",
        },
        { // Night 6: Mimics introduced
            skiffs: 5, merchants: 2, passengers: 0, ghostShips: 0,
            lurkers: 6, flinches: 3, mimics: 2, abyssals: 0, shades: 0,
            spawnInterval: [4, 8], duration: 100,
            desc: "Not everything in the water is what it seems.",
        },
        { // Night 7: Fog
            skiffs: 6, merchants: 2, passengers: 0, ghostShips: 0,
            lurkers: 7, flinches: 4, mimics: 2, abyssals: 0, shades: 0,
            spawnInterval: [4, 7], duration: 100, event: 'fog',
            desc: "Fog rolls in from the north.",
        },
        { // Night 8: Ghost ship + whispers begin
            skiffs: 5, merchants: 3, passengers: 1, ghostShips: 1,
            lurkers: 7, flinches: 3, mimics: 2, abyssals: 0, shades: 0,
            spawnInterval: [4, 7], duration: 100,
            desc: "A derelict drifts from the east channel.",
        },
        { // Night 9: Storm
            skiffs: 7, merchants: 3, passengers: 0, ghostShips: 0,
            lurkers: 8, flinches: 4, mimics: 3, abyssals: 0, shades: 0,
            spawnInterval: [3, 6], duration: 105, event: 'storm',
            desc: "The swell is rising.",
        },
        { // Night 10: New moon
            skiffs: 7, merchants: 3, passengers: 0, ghostShips: 0,
            lurkers: 9, flinches: 5, mimics: 3, abyssals: 0, shades: 0,
            spawnInterval: [3, 6], duration: 105, event: 'newMoon',
            desc: "No moon tonight. Only the beam.",
        },
        { // Night 11: Abyssals introduced + Red Tide
            skiffs: 6, merchants: 3, passengers: 1, ghostShips: 0,
            lurkers: 8, flinches: 4, mimics: 2, abyssals: 1, shades: 0,
            spawnInterval: [3, 6], duration: 110, event: 'redTide',
            desc: "The water glows. Something vast moves beneath.",
        },
        { // Night 12: Shades + fog
            skiffs: 7, merchants: 3, passengers: 0, ghostShips: 0,
            lurkers: 9, flinches: 4, mimics: 2, abyssals: 1, shades: 2,
            spawnInterval: [3, 6], duration: 110, event: 'fog',
            desc: "Whispers from the base of the tower.",
        },
        { // Night 13: Peak difficulty
            skiffs: 9, merchants: 4, passengers: 0, ghostShips: 1,
            lurkers: 10, flinches: 6, mimics: 3, abyssals: 2, shades: 3,
            spawnInterval: [2, 5], duration: 110, event: 'storm',
            desc: "The worst night. Hold fast.",
        },
        { // Night 14: The breather — T4: eerie calm
            skiffs: 3, merchants: 1, passengers: 0, ghostShips: 0,
            lurkers: 0, flinches: 0, mimics: 0, abyssals: 0, shades: 0,
            spawnInterval: [10, 18], duration: 90, event: 'deadCalm',
            desc: "The sea is still. Nothing moves.",
        },
        { // Night 15: The finale
            skiffs: 7, merchants: 3, passengers: 2, ghostShips: 1,
            lurkers: 8, flinches: 5, mimics: 3, abyssals: 2, shades: 4,
            spawnInterval: [2, 5], duration: 120, finale: true,
            desc: "The final night.",
        },
    ],
};

export const UPGRADES = {
    // ── Keeper's Path: wider beam, defense, endurance ──
    lensPolish:    { name: 'Lens Polish',    desc: 'The lens needs cleaning. A polished lens throws a wider beam.',
                     prompt: 'The lens needs cleaning.', effect: 'beam width +10%',
                     path: 'keeper', excludes: 'prismFocus' },
    oilReserve:    { name: 'Oil Reserve',    desc: 'There\'s oil in the supply shed. Extra fuel for the long nights.',
                     prompt: 'There\'s oil in the supply shed.', effect: 'max fuel +15%',
                     path: 'keeper' },
    stormShutters: { name: 'Storm Shutters', desc: 'The shutters need reinforcing. Slows what comes for the tower.',
                     prompt: 'The shutters need reinforcing.', effect: 'shades 30% slower',
                     path: 'keeper', excludes: 'wardStone' },
    fogHorn:       { name: 'Fog Horn',       desc: 'The horn mechanism can be repaired. A blast reveals and scatters what hides in the dark.',
                     prompt: 'The horn mechanism can be repaired.', effect: 'active: reveal + scatter',
                     path: 'keeper', ability: true },

    // ── Watcher's Path: narrow focused beam, aggression, precision ──
    prismFocus:    { name: 'Prism Focus',    desc: 'A prism from the old keeper\'s kit. Narrows the beam but doubles its reach.',
                     prompt: 'A prism from the old keeper\'s kit.', effect: 'beam -20% width, +30% range',
                     path: 'watcher', excludes: 'lensPolish' },
    phosphorOil:   { name: 'Phosphor Oil',   desc: 'This oil burns hotter. Overdrive drains less fuel.',
                     prompt: 'Strange oil in a sealed jar.', effect: 'overdrive drain -40%',
                     path: 'watcher' },
    wardStone:     { name: 'Ward Stone',     desc: 'An old stone etched with marks. Creatures flee faster when lit.',
                     prompt: 'An etched stone on the windowsill.', effect: 'creature flee speed +50%',
                     path: 'watcher', excludes: 'stormShutters' },
    spyglass:      { name: 'Spyglass',       desc: 'A spyglass sits in the drawer. See further, if only for a moment.',
                     prompt: 'A spyglass sits in the drawer.', effect: 'active: zoom beam briefly',
                     path: 'watcher', ability: true },

    // ── Neutral (available to either path) ──
    logBook:       { name: 'Log Book',       desc: 'A proper record keeps the mind sharp. Marks where ships were lost so you can watch those waters.',
                     prompt: 'The logbook needs updating.', effect: 'shows wreck positions',
                     path: 'neutral' },
    tinderBox:     { name: 'Tinder Box',     desc: 'Emergency supplies. Fuel regenerates faster when low.',
                     prompt: 'Emergency supplies in the cellar.', effect: 'fuel regen +50% when below 30%',
                     path: 'neutral' },
};
